DEVELOPER_KEY = "YOUR_YOUTUBE_API_KEY"
YOUTUBE_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
DA_VINCI_MODEL_LIMITATION = 3000 #Don't change this as that is the limit of the Davinci model
OPEN_AI_KEY = 'YOUR_OPEN_AI_KEY'